name: HubChestSelector
main: HubChestSelector\Main
version: 1.0.0
api: 5.36.0

commands:
  hub:
    description: Open the hub selector
    usage: "/hub"
    permission: hubselector.use

permissions:
  hubselector.use:
    default: true
